version: '3'

services:
  user_service:
    image: user_service:1.0
    build:
      context: .
      dockerfile: ./bap-user/Dockerfile
    ports:
      - "4567:8080"
#    depends_on:
#      - user_db
#  user_db:
#    image: postgres:latest


