version: '3'

volumes:
  pgadmin:

services:
  user_service:
    image: user_service:1.0
    build:
      context: .
      dockerfile: ./bap-user/Dockerfile
    ports:
      - "8080:4567"
    depends_on:
      - user_db

  user_db:
    build:
      context: ./bap-user/database
      dockerfile: ./Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - user_db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pwdpwd
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "5050:80"


